package constants

const (
	AuthToken = "BEARER eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDgwNDEyMTYsInR5cGUiOiJleHRlcm5hbCIsInVzZXIiOiJkNjI5MTE0MUB1cmhlbi5jb20ifQ.ZWGZVQ9hioNs909HdOMf4j3NruH1Uu3D8y0zOgp1cGX0IO-SEl2xaulLUDiR4HRyA7fpm-9JdCrzbyxkEaNUQA"
	BasePath = "templates"
)
